### ISSUE TITLE
Need random byte support

### ISSUE THREAD

**Issue by lij55** [faisaltheparttimecoder/mock-data#2]
First of all, thanks for the great tool for generating mock data so easily.
It can generate random data for a lot of different data type.

However, for binary format data, it create random string instead of real binary data.
It would be better to generate real binary format data for 'bytea' format of postgresql.

**Comment by lij55** [comment]
https://github.com/pivotal/mock-data/pull/3

**Comment by faisaltheparttimecoder** [comment]
Thanks @lij55 for the pull request, the pull looks good and its now merged. closing this one
