### ISSUE TITLE
Can't support array type

### ISSUE THREAD

**Issue by lij55** [faisaltheparttimecoder/mock-data#4]
I checked all the types in https://gpdb.docs.pivotal.io/500/ref_guide/data_types.html and it works excellent.

However, it still can't support array type currently. It gives error like ""Unsupported datatypes found: double precision[]""
It would be better to support such type.

**Comment by faisaltheparttimecoder** [comment]
Hi @lij55 

Thanks for reporting the issue, I have pushed the https://github.com/pivotal/mock-data/commit/58fbb90d1999e3550d57462f0ce7954513e16da4 which opens the option to generate random data for array datatypes, currently, it supports these array datatypes.

```
	col_smallint_array      		smallint[],
	col_int_array           		int[],
	col_bigint_array        		bigint[],
	col_character_array     		char(10)[],
	col_char_varying_array  	varchar(10)[],
	col_bit_array 				bit(10)[],
	col_varbit_array 			varbit(4)[],
	col_numeric_array                  numeric[],
	col_numeric_range_array       numeric(5,3)[],
	col_double_precsion_array    float4[],
	col_real_array                         float8[],
	col_money_array                    money[],
	col_time_array                        time without time zone[],
	col_intreval_array                   interval[],
	col_date_array	                date,
	col_time_tz_array 	 		time with time zone,
	col_timestamp_array 	        timestamp with time zone,
	col_timestamp_tz_array         timestamp without time zone,
	col_text_array                         text[]
```
Do you see the need for adding support for other array datatypes ? 

Thanks
Faisal

**Comment by faisaltheparttimecoder** [comment]
Added Support for almost all the datatypes and the commits have been pushed.

https://github.com/pivotal/mock-data/commit/6f72c1691ee4b9feb4a7b46332e4a63aaa8b1841
https://github.com/pivotal/mock-data/commit/4a4bc9460260076884d0203cca0b7e51f97c20b2

All the supported array datatypes can be seen here

https://github.com/pivotal/mock-data/blob/master/demo/postgres/supported-datatypes.sql

Having issues with JSON & XML array's, will work on it sometime later...

**Comment by faisaltheparttimecoder** [comment]
JSON & XML Array support is also added.

https://github.com/pivotal/mock-data/commit/c37b10681d7a33ca91d8615a21873c5d22351536

I believe all major array datatypes are covered ( all datatypes supported can be found [here](https://github.com/pivotal/mock-data/blob/master/demo/postgres/supported-datatypes.sql) ), so closing up the issue.

Please reopen if I missed anything ...

**Comment by lij55** [comment]
Thank you very much!!
