### ISSUE TITLE
Can't install: `no such file or directory`

### ISSUE THREAD

**Issue by ghost** [faisaltheparttimecoder/mock-data#8]
## Command  
`./mockd-mac postgres -help`

## What occurred
I'm in the desktop folder where the mockd-mac file is located. Somehow it is unable to find it.
```
desktop$ sudo ./mockd-mac postgres --help
Password:
sudo: ./mockd-mac: command not found
desktop$ bin/mockd-mac postgres -help
-bash: bin/mockd-mac: No such file or directory
```

## What you expected to occur
To return help menu.

**Comment by faisaltheparttimecoder** [comment]
Hello @tiotolstoy , 

Any reason for running with `sudo` ? this works for me

```
$ chmod +x mockd-mac
$ ./mockd-mac postgres -help
Usage of postgres:
  -d string
    	The database name where the table resides (default "postgres")
  -debug
    	Print debug information
  -h string
    	The hostname that can be used to connect to the database (default "localhost")
  -i	Ignore checking and fixing constraint issues
  -n int
    	The total number of mocked rows that is needed (default 1)
  -p int
    	The port that is used by the database engine (default 5432)
  -t string
    	The table name to be filled in with mock data
  -u string
    	The username that can be used to connect to the database (default "postgres")
  -w string
    	The password for the user that can be used to connect to the database
  -x	Mock all the tables in the database
```

**Comment by ghost** [comment]
It prompted me to use sudo.

This doesn't work for example. I don't have that much experience on the
command-line so I'm sure it something I'm doing wrong just can't figure it
out. :((
```
desktop$ chmod +x mockd-mac -help

chmod: -help: No such file or directory

```


When I run just `chmod +x mockd-mac` there's no error or success message.

**Comment by faisaltheparttimecoder** [comment]
> When I run just `chmod +x mockd-mac` there's no error or success message.

That is how it is supposed to work in linux, you dont get any feedback if the command is successful. run `ls -ltr` to know if the `mockd-mac` now has execute privilege.

>  desktop$ chmod +x mockd-mac -help
chmod: -help: No such file or directory

That error occurred since the `chmod` is trying to locate a file which is named `-help`, which doesn't exists on your current directory, if you want to know the help of `chmod` command then you can use this `chmod help`

**Comment by ghost** [comment]
Understood, thank you.  🙏
